// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: copyfrom.go

package repository

import (
	"context"
)

// iteratorForInsertUserPrayers implements pgx.CopyFromSource.
type iteratorForInsertUserPrayers struct {
	rows                 []InsertUserPrayersParams
	skippedFirstNextCall bool
}

func (r *iteratorForInsertUserPrayers) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForInsertUserPrayers) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ID,
		r.rows[0].UserID,
		r.rows[0].Name,
		r.rows[0].Year,
		r.rows[0].Month,
		r.rows[0].Day,
	}, nil
}

func (r iteratorForInsertUserPrayers) Err() error {
	return nil
}

func (q *Queries) InsertUserPrayers(ctx context.Context, arg []InsertUserPrayersParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"prayer"}, []string{"id", "user_id", "name", "year", "month", "day"}, &iteratorForInsertUserPrayers{rows: arg})
}
