// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Coupon struct {
	Code               string             `json:"code"`
	InfluencerUsername string             `json:"influencer_username"`
	Quota              int16              `json:"quota"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	DeletedAt          pgtype.Timestamptz `json:"deleted_at"`
}

type Invoice struct {
	ID          pgtype.UUID        `json:"id"`
	UserID      pgtype.UUID        `json:"user_id"`
	PlanID      pgtype.UUID        `json:"plan_id"`
	RefID       string             `json:"ref_id"`
	CouponCode  pgtype.Text        `json:"coupon_code"`
	TotalAmount int32              `json:"total_amount"`
	QrUrl       string             `json:"qr_url"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Payment struct {
	ID         pgtype.UUID        `json:"id"`
	UserID     pgtype.UUID        `json:"user_id"`
	InvoiceID  pgtype.UUID        `json:"invoice_id"`
	AmountPaid int32              `json:"amount_paid"`
	Status     string             `json:"status"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Plan struct {
	ID               pgtype.UUID        `json:"id"`
	Type             string             `json:"type"`
	Name             string             `json:"name"`
	Price            int32              `json:"price"`
	DurationInMonths int16              `json:"duration_in_months"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	DeletedAt        pgtype.Timestamptz `json:"deleted_at"`
}

type Prayer struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
	Name   string      `json:"name"`
	Status string      `json:"status"`
	Year   int16       `json:"year"`
	Month  int16       `json:"month"`
	Day    int16       `json:"day"`
}

type RefreshToken struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Revoked   bool               `json:"revoked"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

type Subscription struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	PlanID    pgtype.UUID        `json:"plan_id"`
	PaymentID pgtype.UUID        `json:"payment_id"`
	StartDate pgtype.Timestamptz `json:"start_date"`
	EndDate   pgtype.Timestamptz `json:"end_date"`
}

type Task struct {
	ID          pgtype.UUID `json:"id"`
	UserID      pgtype.UUID `json:"user_id"`
	Name        string      `json:"name"`
	Description string      `json:"description"`
	Checked     bool        `json:"checked"`
}

type User struct {
	ID          pgtype.UUID        `json:"id"`
	Email       string             `json:"email"`
	Password    string             `json:"password"`
	Name        string             `json:"name"`
	Coordinates pgtype.Point       `json:"coordinates"`
	City        string             `json:"city"`
	Timezone    string             `json:"timezone"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}
